### ISSUE TITLE
a11y - Colors in Base UI Components

### ISSUE THREAD

**Issue by mxrcx** [hpi-schul-cloud/nuxt-client#1148]
**_### Only necessary for WCGA Level AA and AAA requirements, we currently need Level A_**

Contrast between grey color #aaaaaa and white background #ffffff is too low. 
Suggestion: Change #aaaaaa to #595959.

Also, contrast between orange color #e98404 and white background #ffffff is too low. 
Suggestion: Change #e98404.

**Occurences:**
Base Input: Date, Multiple, Time, Default
Base UI: Base Link, Base Select, Base Blockquote, Base Button, Base Modal Default, Base Modal Dialog, Base Modal Loading

**Comment by MLuderich** [comment]
Colours have been reworked since this issue was created. Closed it for now.
