### ISSUE TITLE
implement Concept for feature flags

### ISSUE THREAD

**Issue by adrianjost** [hpi-schul-cloud/nuxt-client#126]
Features should be easy to disable without new deployment

**Comment by ChrisWeissmann** [comment]
In the current client feature are enabled and disabled via enviroment variables. If we want to do it without a new deployment I think we should go into fine graind controll. My idea would be to do something that is simular to permissions but for individual features. Then during the login we save what feature permissions are available for the user in the store and adjust the view appropiatly. Therefore we can change features in the db during runtime. 
What are your thoughts?
