### ISSUE TITLE
Refactor BaseModal

### ISSUE THREAD

**Issue by adrianjost** [hpi-schul-cloud/nuxt-client#132]
Accessibility:
- Elemente außerhalb des Modals dürfen nicht fokusierbar sein (keyboard nav)
- aria attribute fehlen
- Button zum triggern muss teil der Komponente sein

you know best

**Comment by smyth64** [comment]
> Accessibility:
> 
> * Button zum triggern muss teil der Komponente sein
> 

Das versteh ich nicht ganz. Warum muss der Button ein Teil der Komponente sein? Ich möchte ja das Modal eventuell programmatisch triggers bzw über einen Link etc. Oder wie ist das gemeint?

**Comment by adrianjost** [comment]
@smyth64 Also ich habe Roberts Erklärung so verstanden:

Man triggert das modal eigentlich immer über eine User Action. Von der accessibility her müsste der Trigger daher ein `<Button>` sein (kein Link!). Um das zu enforcen sollte der Button Teil der Komponente sein. Dieser Button muss nicht zwingend Style haben (`display: contents` ginge bspw. hierfür super), aber semantisch muss er da sein. Der Button-Content selbst könnte dann ja wieder ein slot sein.

**Comment by smyth64** [comment]
@adrianjost Alles klar Prinzip hab ich verstanden.

Gibt es dazu ein Beispiel bzw ein Best Practice? Ich hab mal auf w3 und Mozilla geschaut, aber da leider kein Beispiel gefunden, wo der Button Aria Attribute hat. Nur das Modal hat 
https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/alertdialog.html
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role

Hier ist eins basierend auf React, aber im Button find ich auch keine Aria Attribute.
https://github.com/davidtheclark/react-aria-modal


Vielleicht kann da @rodebert weiterhelfen.
