### ISSUE TITLE
"Aufgabe öffnen" link at wrong position in Task list

### ISSUE THREAD

**Issue by jukey** [hpi-schul-cloud/nuxt-client#1664]
I do not have an account for the ticketsystem mentioned above, nor do I know how to get access. I just wanted to drop the following screenshot showing the links to access task details is not at the correct place:
![grafik](https://user-images.githubusercontent.com/295928/107888675-1d7eb300-6f0e-11eb-8997-a96b1a2df20a.png)

I am using Mozilla Firefox 84.0.2  and Ubuntu 20.04.1

**Comment by MLuderich** [comment]
This should be solved with new task overview, fully replacing the old overview with version 27.0.0.
