### ISSUE TITLE
Falsche Zertifikate für Storybook & VuePress

### ISSUE THREAD

**Issue by Chaostheorie** [hpi-schul-cloud/nuxt-client#1929]
Alle Deployments, außer production nuxt, (verlinkt in u. a. README.md) haben ein falsches Zertifikat gesetzt. Diese Domains benutzen das Zertifikat für hpi-schul-cloud.de (mit alts) aber die alt domains des Zertifikats enthalten nicht die Domains für die verschiedene Deployments. Dies kann durch das Hinzufügen der neuen alts gelöst werden. Dieses falsch verwendete Zertifikat macht den Zugriff auf die Deployment mit einem Browser nicht möglich, da HSTS aktiviert ist.

Beispiel: <https://vuepress.test.hpi-schul-cloud.de/>

**Comment by mamutmk5** [comment]
Hallo @Chaostheorie, danke für den Hinweis das wir die README.md anpassen sollten. Dies haben wir leider vergessen als wir das Projekt auf eine neue CI/CD Struktur umgebaut haben, die jetzt weitestgehend auf github actions besteht.

**Comment by Chaostheorie** [comment]
Na ja, in der Zwischenzeit sind alle Links außer das Nuxt Production Environment (welches auch auf einen redirect leitet) und die CI nicht mehr funktional. Ist es überhaupt noch geplant, die offenen Vuepress und Storybook Instanzen anzubieten? Die Subdomains von diesen Services scheinen nicht mehr in den Namen für das Zertifikat für dbilduingscloud.de enthalten zu sein.

**Comment by Loki-Afro** [comment]
@Chaostheorie storybook gibts nicht mehr vuepress auch nicht, hat das letzte größere dependency update nicht überlebt afaik
