### ISSUE TITLE
Address Build warnings

### ISSUE THREAD

**Issue by ChrisWeissmann** [hpi-schul-cloud/nuxt-client#212]
Getting the warning:
`[WARN] vendor has been deprecated due to webpack4 optimization`
And
`Please use build.postcss in your nuxt.config.js instead of an external config file.`
Should be addressed.

**Comment by ChrisWeissmann** [comment]
I just looked into this a bit and seems like storybook wants an external config file while nuxt doesn't like it. 
Webpack should support adding the post css loader inline instead of in a config file but I haven't had any luck with it. If someone knows more please let me know so I can learn about the correct way :) @adrianjost you maybe? 😄

**Comment by adrianjost** [comment]
I will take a look on it on friday or the weekend. Stay tuned 😅

**Comment by adrianjost** [comment]
I also haven't found a good solution :/

I haven't found a solution to enable postcss in storybook without the config file.
When the breaking nuxt change is only, that they do not import the postcss.config.js anymore, we can simply do this manually with `const postcss = require("./postcss.config");`. and `build.postcss = postcss` inside the nuxt.config.js.

I wouldn't put to much time into it yet and wait until something breaks.
